#ifndef ANALOG_HANDLER_TYPES_H
#define ANALOG_HANDLER_TYPES_H

#include "pico/stdlib.h"

#define ADC_MIN_PIN_ID 26
#define ADC_MAX_PIN_ID 28

enum
{
    ADC_C_INIT_PIN,
    ADC_C_DEINIT_PIN,
    ADC_C_SAMPLE_ONCE,
    ADC_C_SAMPLE_ONCE_BLOCKING,
    ADC_C_GET_RESULT,
    ADC_C_START_SAMPLER,
    ADC_C_READ_SAMPLER,
    ADC_C_STOP_SAMPLER,
};

enum
{
    ADC_E_OK,
    ADC_E_PIN_INDEX_INVALID,
    ADC_E_ALREADY_INITIALIZED,
    ADC_E_NOT_INITIALIZED,
    ADC_E_COMMAND_UNKNOWN,
    ADC_E_SAMPLER_RUNNING,
    ADC_E_SAMPLER_NOT_RUNNING,
    ADC_E_SAMPLER_BUSY,
    ADC_E_CHANNEL_MISMATCH,

    ADC_E_UNKNOWN,
};

#endif